from typing import Dict, Any, List
from app.models.compliance_models import ComplianceAnalysis
from app.models.risk_models import RiskAnalysis
from app.models.recommendation_models import RecommendationAnalysisLLM
from app.services.llm import llm_service
from app.prompts.recommendation_prompt import SYSTEM_PROMPT
from app.utils.logger import logger
from langchain_core.prompts import ChatPromptTemplate


class RecommendationAgent:
    """Agent responsible for generating remediation recommendations from compliance and risk analysis."""

    def __init__(self) -> None:
        """Initialize the RecommendationAgent by binding the LLM with structured output in JSON mode."""
        logger.info("Initializing RecommendationAgent with structured output...")
        try:
            self._structured_llm = llm_service.with_structured_output(
                RecommendationAnalysisLLM,
                method="json_mode"
            )
            self._prompt_template = ChatPromptTemplate.from_messages([
                ("system", SYSTEM_PROMPT),
                ("human", "Compliance & Risk Context to Assess:\n\n{findings_str}")
            ])
            self._chain = self._prompt_template | self._structured_llm
        except Exception as e:
            logger.error(f"Failed to initialize RecommendationAgent: {e}", exc_info=True)
            raise e

    def recommend(
        self,
        compliance_analysis: ComplianceAnalysis,
        risk_analysis: RiskAnalysis
    ) -> RecommendationAnalysisLLM:
        """Analyze compliance and risk outputs to generate actionable remediation recommendations.

        Args:
            compliance_analysis (ComplianceAnalysis): Calculated compliance findings.
            risk_analysis (RiskAnalysis): Calculated risk assessments.

        Returns:
            RecommendationAnalysisLLM: Pydantic model containing recommended actions and steps.
        """
        logger.info("Recommendation Agent assessment started")
        findings = compliance_analysis.findings
        logger.info(f"Number of findings: {len(findings)}")

        # Scenario: Insufficient evidence (Requirement 9)
        if compliance_analysis.overall_status == "insufficient_evidence":
            logger.info("Compliance status is insufficient_evidence. Skipping recommendation generation.")
            return RecommendationAnalysisLLM(
                recommendations=[],
                summary="Remediation recommendations skipped: compliance evidence was insufficient to perform assessment."
            )

        # Scenario: All findings are compliant with no residual risks (Requirement 8)
        all_compliant = all(f.status == "compliant" for f in findings)
        if all_compliant and len(risk_analysis.assessments) == 0:
            logger.info("All findings are compliant with no residual risks. Returning empty recommendations.")
            return RecommendationAnalysisLLM(
                recommendations=[],
                summary="No remediation actions are currently required because all evaluated controls are compliant."
            )

        # Build risk lookup map by finding_id
        risk_map = {a.finding_id: a for a in risk_analysis.assessments}

        findings_formatted = []
        for idx, f in enumerate(findings):
            fid = f"finding_{idx}"
            risk_info = risk_map.get(fid)

            # Ignore compliant findings unless they have a residual risk (Requirement 8)
            if f.status == "compliant" and not risk_info:
                continue

            risk_str = "No risk identified (compliant control)."
            if risk_info:
                risk_str = (
                    f"Risk Level: {risk_info.risk_level}\n"
                    f"Risk Score: {risk_info.risk_score}\n"
                    f"Risk Rationale: {risk_info.rationale}"
                )

            findings_formatted.append(
                f"Finding ID: {fid}\n"
                f"Control: {f.control}\n"
                f"Compliance Status: {f.status}\n"
                f"Company Requirement: {f.company_requirement}\n"
                f"Regulatory Requirement: {f.regulatory_requirement}\n"
                f"Compliance Reasoning: {f.reasoning}\n"
                f"=== RISK ASSESSMENT ===\n{risk_str}"
            )

        findings_str = "\n\n---\n\n".join(findings_formatted)

        try:
            # Execute LLM chain
            result: RecommendationAnalysisLLM = self._chain.invoke({
                "findings_str": findings_str
            })

            logger.info(f"Recommendations generated by LLM: count={len(result.recommendations)}")
            return result

        except Exception as e:
            logger.error(f"RecommendationAgent LLM execution failed: {e}", exc_info=True)
            raise ValueError(f"Recommendation generation execution failed: {e}")
