from typing import Dict, Any, List
from app.models.compliance_models import ComplianceAnalysis
from app.models.risk_models import RiskAnalysisLLM, RiskFactorAssessment
from app.services.llm import llm_service
from app.prompts.risk_prompt import SYSTEM_PROMPT
from app.utils.logger import logger
from langchain_core.prompts import ChatPromptTemplate


class RiskAgent:
    """Agent responsible for identifying and assessing compliance-related risk factors."""

    def __init__(self) -> None:
        """Initialize the RiskAgent by binding the LLM with structured output in JSON mode."""
        logger.info("Initializing RiskAgent with structured output...")
        try:
            self._structured_llm = llm_service.with_structured_output(
                RiskAnalysisLLM,
                method="json_mode"
            )
            self._prompt_template = ChatPromptTemplate.from_messages([
                ("system", SYSTEM_PROMPT),
                ("human", "Compliance Findings to Assess:\n\n{findings_str}")
            ])
            self._chain = self._prompt_template | self._structured_llm
        except Exception as e:
            logger.error(f"Failed to initialize RiskAgent: {e}", exc_info=True)
            raise e

    def assess(self, compliance_analysis: ComplianceAnalysis) -> RiskAnalysisLLM:
        """Evaluate compliance findings and generate intermediate risk factors.

        Args:
            compliance_analysis (ComplianceAnalysis): Calculated compliance findings.

        Returns:
            RiskAnalysisLLM: Pydantic model containing intermediate severity, likelihood, and impact assessments.
        """
        logger.info("Risk Agent evaluation started")
        findings = compliance_analysis.findings
        logger.info(f"Number of compliance findings: {len(findings)}")

        # Scenario: All findings are compliant
        all_compliant = all(f.status == "compliant" for f in findings)
        if all_compliant:
            logger.info("All findings are compliant. Returning deterministic low-risk response.")
            return RiskAnalysisLLM(
                assessments=[],
                summary="No material compliance gaps were identified. All evaluated controls are compliant."
            )

        # Format findings for human prompt
        findings_formatted = []
        for idx, f in enumerate(findings):
            evidence_texts = [
                f"- [File: {ev.filename}] {ev.text}"
                for ev in f.evidence
            ]
            evidence_str = "\n".join(evidence_texts) if evidence_texts else "No evidence text available."

            findings_formatted.append(
                f"Finding ID: finding_{idx}\n"
                f"Control: {f.control}\n"
                f"Status: {f.status}\n"
                f"Company Requirement: {f.company_requirement}\n"
                f"Regulatory Requirement: {f.regulatory_requirement}\n"
                f"Reasoning: {f.reasoning}\n"
                f"Evidence Snippets:\n{evidence_str}"
            )

        findings_str = "\n\n---\n\n".join(findings_formatted)

        try:
            # Execute LLM chain
            result: RiskAnalysisLLM = self._chain.invoke({
                "findings_str": findings_str
            })

            logger.info(f"Risk factors generated by LLM: count={len(result.assessments)}")
            return result

        except Exception as e:
            logger.error(f"RiskAgent LLM execution failed: {e}", exc_info=True)
            raise ValueError(f"Risk analysis execution failed: {e}")
